# version: 2.1
# orbs:
#   node: circleci/node@5.0.2
#   cypress: cypress-io/cypress@2.1.0

# jobs:
#   build_and_test:
#     executor: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm 
#       - run:
#           command: npm test
#           name: Run tests
#       - run:
#           command: npm run build
#           name: Build app
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - .
# workflows:
#   test_my_app:
#     jobs:
#       - build_and_test


version: 2.1
orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@2.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_roed_to_aid_fe:
    jobs:
      - cypress/run:
          start: npm start
      - build